---
services:
  traefik:
    image: traefik:v3.7
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.role == manager
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.middlewares.sts-headers.headers.STSIncludeSubdomains: "true"
        traefik.http.middlewares.sts-headers.headers.STSSeconds: "31536000"
        traefik.http.routers.dashboard.entrypoints: "websecure"
        # traefik.http.routers.dashboard.middlewares: "sts-headers,auth-svcs"
        traefik.http.routers.dashboard.middlewares: "sts-headers"
        traefik.http.routers.dashboard.rule: "Host(`proxy.${SERVICES_DOMAIN}`)"
        traefik.http.routers.dashboard.service: "api@internal"
        traefik.http.routers.dashboard.tls: "true"
        # traefik.http.routers.traefik.tls.certresolver: "letsencrypt"
        traefik.http.services.traefik.loadbalancer.server.port: "443"
    environment:
      TZ: Europe/Berlin
    command:
      --accesslog.fields.names.StartUTC=drop
      --accesslog=true
      --api.dashboard=true
      # --certificatesresolvers.letsencrypt.acme.email=${ADMIN_MAIL}
      # --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      # --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      # --certificatesresolvers.letsencrypt.acme.storage=/ssl/acme.json
      --entrypoints.ts-dns.address=:41144/tcp
      --entrypoints.ts-dns.http.aliasHeadersStrategy=delete
      --entrypoints.ts-filetransfer.address=:30033/tcp
      --entrypoints.ts-filetransfer.http.aliasHeadersStrategy=delete
      --entrypoints.ts-raw.address=:10011/tcp
      --entrypoints.ts-raw.http.aliasHeadersStrategy=delete
      --entrypoints.ts-ssh.address=:10022/tcp
      --entrypoints.ts-ssh.http.aliasHeadersStrategy=delete
      --entrypoints.ts-voice.address=:9987/udp
      --entrypoints.ts-voice.http.aliasHeadersStrategy=delete
      --entrypoints.ts-voice.proxyProtocol.trustedIPs=127.0.0.1/32,14.84.0.1/16
      --entrypoints.web.address=:80
      --entrypoints.web.http.aliasHeadersStrategy=delete
      --entrypoints.web.http.redirections.entrypoint.permanent=true
      --entrypoints.web.http.redirections.entrypoint.scheme=https
      --entrypoints.web.http.redirections.entrypoint.to=websecure
      --entrypoints.websecure.address=:443
      --entryPoints.websecure.http.aliasHeadersStrategy=delete
      --entrypoints.websecure.http.tls=true
      --log.level=INFO
      --metrics.prometheus=true
      --providers.file.filename=/ssl/tls.yml
      --providers.swarm.endpoint=unix:///var/run/docker.sock
      --providers.swarm.exposedbydefault=false
      --providers.swarm.network=proxy
      --providers.swarm.watch=true
    ports:
      - mode: host
        published: 80
        target: 80
      - mode: host
        published: 443
        target: 443
      - mode: host
        protocol: udp
        published: 9987
        target: 9987
      - mode: host
        protocol: tcp
        published: 10011
        target: 10011
      - mode: host
        protocol: tcp
        published: 10022
        target: 10022
      - mode: host
        protocol: tcp
        published: 30033
        target: 30033
      - mode: host
        protocol: tcp
        published: 41144
        target: 41144
    networks:
      - proxy
    volumes:
      - ssl:/ssl
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  proxy:
    attachable: true
    driver: overlay
    name: proxy

volumes:
  ssl:
