---
forgejo_runner_additional_groups:
  - docker
forgejo_runner_connections:
  codeberg_general:
    name: "{{ ansible_hostname }}"
    capacity: 4
    labels:
      - docker
      - internet
      - kurthos
      - privileged
    token: "{{ lookup('env', 'FORGEJO_CODEBERG_GENERAL_TOKEN') }}"
    url: https://codeberg.org/
  codeberg_altosteiti:
    name: "{{ ansible_hostname }}"
    capacity: 4
    labels:
      - altosteiti
      - docker
      - internet
      - kurthos
      - privileged
    token: "{{ lookup('env', 'FORGEJO_CODEBERG_ALTOSTEITI_TOKEN') }}"
    url: https://codeberg.org/
forgejo_runner_base_url: https://code.forgejo.org/forgejo/runner/releases/download
forgejo_runner_version: 12.7.3

# Automatical values. Dont touch these.
forgejo_runner_arch: "{{ package_architectures[ansible_facts['architecture']] }}"
forgejo_runner_filename: "forgejo-runner-{{ forgejo_runner_version }}-linux-{{ forgejo_runner_arch }}"
forgejo_runner_url: "{{ forgejo_runner_base_url }}/v{{ forgejo_runner_version }}/{{ forgejo_runner_filename }}"
