[env]
# Contact email for administration and law enforcement.
ADMIN_EMAIL=""

# DNS domain used by specific apps in the cluster.
# Deprecated
APP_DOMAIN=""

# Default DNS domain used by all apps in the cluster.
APPS_DOMAIN=""

# Amount of cpus used by the minikube cluster.
MINIKUBE_CPUS="4"

# Amount of memory used by the minikube cluster.
MINIKUBE_MEMORY="16384"

# Default DNS domain used by all services in the cluster.
SERVICES_DOMAIN=""


#########################################################################################
## Swarm Services
#########################################################################################

## Authentik

# Password for the Authentik admin user configured during the initial startup.
# Use `pwgen 24` to generate a new password.
AUTHENTIK_BOOTSTRAP_PASSWORD=""

# API Token for the Authentik admin user configured during the initial startup.
# Use `pwgen 24` to generate a new password.
AUTHENTIK_BOOTSTRAP_TOKEN=""

# Database password used by the Authentik app.
# Use `pwgen 24` to generate a new password.
AUTHENTIK_PG_PASS=""

# Token for the authentik apps proxy for registering with the authentik server.
AUTHENTIK_PROXY_APPS_TOKEN=""

# Token for the authentik services proxy for registering with the authentik server.
AUTHENTIK_PROXY_SVCS_TOKEN=""

# Secret key used by the Authentik app.
# Use `openssl rand -base64 60 | tr -d '\n'` to generate a new key.
AUTHENTIK_SECRET_KEY=""

# Container image tag used for the Authentik app.
AUTHENTIK_TAG="2025.2.4"


#########################################################################################
## Swarm Apps
#########################################################################################

## Grafana

# Password for the Grafana admin user.
GRAFANA_SECURITY_ADMIN_PASSWORD=""

## Kimai

# Password for the Kimai admin user.
KIMAI_ADMIN_PASSWORD=""

# Database password used by the Kimai app.
KIMAI_DB_PASSWORD=""

# Database root password for administration purposes.
KIMAI_DB_ROOT_PASSWORD=""

# Email address with which the Kimai app sends emails.
KIMAI_MAILER_FROM=""

## Nextcloud

# Database password used by the Nextcloud app.
NEXTCLOUD_DB_PASSWORD=""

# Database root password for administration purposes.
NEXTCLOUD_DB_ROOT_PASSWORD=""

# Redis password used by the Nextcloud app.
NEXTCLOUD_REDIS_PASSWORD=""
