[env]
# Contact email for administration and law enforcement.
ADMIN_EMAIL=""

# DNS domain used by specific apps in the cluster.
# Deprecated
APP_DOMAIN=""

# Default DNS domain used by all apps in the cluster.
APPS_DOMAIN=""

# DNS domain used by feaby apps in the cluster.
FEABY_DOMAIN=""

# Amount of cpus used by the minikube cluster.
MINIKUBE_CPUS="4"

# Amount of memory used by the minikube cluster.
MINIKUBE_MEMORY="16384"

# Default DNS domain used by all services in the cluster.
SERVICES_DOMAIN=""

# Basic auth credentials for the Traefik dashboard.
TRAEFIK_BASIC_AUTH=""


#########################################################################################
## Swarm Services
#########################################################################################

## Authentik

# Password for the Authentik admin user configured during the initial startup.
# Use `pwgen 24` to generate a new password.
AUTHENTIK_BOOTSTRAP_PASSWORD=""

# API Token for the Authentik admin user configured during the initial startup.
# Use `pwgen 24` to generate a new password.
AUTHENTIK_BOOTSTRAP_TOKEN=""

# Container image name used for the Authentik app.
AUTHENTIK_IMAGE="ghcr.io/goauthentik/server"

# Database password used by the Authentik app.
# Use `pwgen 24` to generate a new password.
AUTHENTIK_PG_PASS=""

# Token for the authentik apps proxy for registering with the authentik server.
AUTHENTIK_PROXY_APPS_TOKEN=""

# Token for the feaby apps proxy for registering with the authentik server.
AUTHENTIK_PROXY_FEABY_APPS_TOKEN=""

# Token for the authentik services proxy for registering with the authentik server.
AUTHENTIK_PROXY_SVCS_TOKEN=""

# Secret key used by the Authentik app.
# Use `openssl rand -base64 60 | tr -d '\n'` to generate a new key.
AUTHENTIK_SECRET_KEY=""

# Container image tag used for the Authentik app.
AUTHENTIK_TAG="2025.2.4"

## Grafana

# Password for the Grafana admin user.
GRAFANA_SECURITY_ADMIN_PASSWORD=""

# Basic auth credentials for the Grafana service dashboards.
GRAFANA_BASIC_AUTH=""


#########################################################################################
## Swarm Apps
#########################################################################################

## Journal

# Secret key used for encrypting the journal data.
# Use `openssl rand -base64 32 | tr -d '\n'` to generate a new key.
JOURNAL_CIPHER_KEY=""

# Container tag of the journal app image.
JOURNAL_CONTAINER_TAG="1.0.0"

# Database container tag of the journal app image.
JOURNAL_DATABASE_CONTAINER_TAG="17.4"

# Database password used by the journal app.
# Use `pwgen 24` to generate a new password.
JOURNAL_DATABASE_PASSWORD=""

# Secret key for verifying the integrity of signed cookies.
# Use `pwgen 32` to generate a new key.
JOURNAL_SECRET_KEY_BASE=""

# This is to make sure sharing token IVs are the same so we can find posts from a public
# route parameter.
# Use `openssl rand -base64 16 | tr -d '\n'` to generate a new IV.
JOURNAL_SHARING_TOKEN_CIPHER_IV=""

## Kimai

# Password for the Kimai admin user.
KIMAI_ADMIN_PASSWORD=""

# Database password used by the Kimai app.
KIMAI_DB_PASSWORD=""

# Database root password for administration purposes.
KIMAI_DB_ROOT_PASSWORD=""

# Email address with which the Kimai app sends emails.
KIMAI_MAILER_FROM=""

## Memos

# Container tag of the memos app image.
MEMOS_CONTAINER_TAG="0.24.2"

# Database password used by the memos app.
# Use `pwgen 24` to generate a new password.
MEMOS_DATABASE_PASSWORD=""

# Database root password for the memos database.
# Use `pwgen 24` to generate a new password.
MEMOS_DATABASE_ROOT_PASSWORD=""

# Container tag of the mariadb image used by the memos app.
MEMOS_MARIADB_CONTAINER_TAG="10.5"

## Nextcloud

# Database password used by the Nextcloud app.
NEXTCLOUD_DB_PASSWORD=""

# Database root password for administration purposes.
NEXTCLOUD_DB_ROOT_PASSWORD=""

# Redis password used by the Nextcloud app.
NEXTCLOUD_REDIS_PASSWORD=""
