[env]
'_'.python.venv.path = ".venv"

# The kubernetes version used for the minikube cluster.
# Also check the kubectl version in the [tools] section when changing this.
MINIKUBE_KUBERNETES_VERSION="1.30.0"

# The amount of nodes spawned for the minikube cluster.
MINIKUBE_NODE_COUNT="3"

# The profile name of the minikube cluster.
MINIKUBE_PROFILE="infrastructure"

[settings]
experimental = true
python.uv_venv_auto = true

[tools]
"aqua:lycheeverse/lychee" = "latest"
minikube = "latest"
uv = "latest"
