[project]
name = "infrastructure"
version = "0.1.0"
description = "IaC for chroni.cc, kurthos.com and kurthos.studio."
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
]
