collections:
  - name: ansible.netcommon
    version: 7.1.0
  - name: ansible.posix
    version: 1.5.4
  - name: ansible.utils
    version: 4.1.0
  - name: ansible.windows
    version: 2.5.0
  - name: chronicc.bouquet
    source: git+https://github.com/chronicc/ansible-collection-bouquet
    type: git
    version: 1.0.0
  - name: community.docker
    version: 3.12.2
  - name: community.general
    version: 7.4.0
  - name: community.mysql
    version: 3.10.3
  - name: community.postgresql
    version: 3.6.1
  - name: community.zabbix
    version: 3.1.2
  - name: community.windows
    version: 2.3.0
  - name: prometheus.prometheus
    version: 0.24.1

roles:
  - name: chronicc.bash
    version: 0.1.3
  - name: cimon-io.asdf
    version: v1.1.0
  - name: ctorgalson.nerdfonts
    version: v1.0.1
  - name: geerlingguy.apache
    version: 4.0.0
  - name: geerlingguy.composer
    version: 1.9.2
  - name: geerlingguy.docker
    version: 7.4.1
  - name: geerlingguy.mysql
    version: 4.3.4
  - name: geerlingguy.php
    version: 6.0.0
  - name: geerlingguy.postgresql
    version: 3.5.2
  - name: derJD.journald
    version: 0.0.1
