#!/usr/bin/env bash
# shellcheck disable=SC2154
# mise description="Install project dependencies"
# mise depends=["python:install"]

cd "$root" || exit 1

if [ ! -f .mise.local.toml ] && [ -f .mise.local.template.toml ]
then
    cp .mise.local.template.toml .mise.local.toml
fi
