---
all:
  ##
  ## Node Overview
  ##
  hosts:
    beacon01:
      ansible_host: beacon01.kurthos.site
    libre:
      ansible_host: libre.kurthos.site
    worker01:
      ansible_host: worker01.kurthos.site
    worker02:
      ansible_host: worker02.kurthos.site

  ##
  ## Node Grouping
  ##
  children:

    ##
    ## Infrastructure Groups
    ##

    # Nodes that act as gateways and turn services.
    beacons:
      hosts:
        beacon01:

    # Nodes that run containers.
    container_nodes:
      hosts:
        beacon01:
        libre:
        worker01:
        worker02:

    forgejo_runners:
      hosts:
        worker02:

    # Nodes that are responsible for controlling the cluster.
    swarm_control_nodes:
      hosts:
        beacon01:
        libre:
        worker01:

    # Nodes that are responsible for running the workloads.
    swarm_worker_nodes:
      hosts:
        beacon01:
        worker01:
        worker02:

    # Nodes that are used for human input
    workstations:
      hosts:
        libre:
