#!/usr/bin/env bash
# mise description="Install python requirements"

# We need to install pip-tools first to get access to pip-compile
if ! command -v pip-compile 2>&1 >/dev/null
then
    echo ">>> Installing pip-tools"
    pip install pip-tools
fi

# If requirements.txt doesn't exist, the repository probably is a fresh clone
# so we can do all the initial python setup here
if [ ! -f requirements.txt ]
then
    echo ">>> Compiling requirements.txt"
    pip-compile --output-file=requirements.txt requirements.in
fi

echo ">>> Installing python requirements"
pip install --requirement=requirements.txt
