#!/usr/bin/env bash
# mise description="Upgrade python requirements"

echo ">>> Compiling requirements.txt with updated dependencies"
pip-compile --upgrade --output-file=requirements.txt requirements.in


echo ">>> Upgrading pip"
pip install --upgrade pip


echo ">>> Upgrading python requirements"
pip install --requirement=requirements.txt
