---
services:
  db:
    image: mariadb:10
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.hostname==rs1
          - node.labels.environment==production
          - node.labels.proxy!=true
      replicas: 1
    volumes:
      - database:/var/lib/mysql
    environment:
      - MARIADB_DATABASE=kimai
      - MARIADB_USER=kimai
      - MARIADB_PASSWORD=${KIMAI_DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${KIMAI_DB_ROOT_PASSWORD}
    command: --default-storage-engine innodb
    networks:
      - default

  kimai:
    image: kimai/kimai2:apache
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.hostname==rs1
          - node.labels.environment==production
          - node.labels.proxy!=true
      replicas: 1
      labels:
        traefik.enable: "true"
        traefik.http.routers.kimai.entrypoints: "websecure"
        traefik.http.routers.kimai.middlewares: "sts-headers,auth-apps"
        traefik.http.routers.kimai.rule: "Host(`kimai.${APPS_DOMAIN}`)"
        traefik.http.routers.kimai.tls: "true"
        traefik.http.routers.kimai.tls.certresolver: "letsencrypt"
        traefik.http.services.kimai.loadbalancer.server.port: "8001"
        traefik.swarm.network: "proxy"
    environment:
      - ADMINMAIL=${ADMIN_MAIL}
      - ADMINPASS=${KIMAI_ADMIN_PASSWORD}
      - DATABASE_URL=mysql://kimai:${KIMAI_DB_PASSWORD}@db/kimai
      - TRUSTED_HOSTS=kimai.${APPS_DOMAIN},traefik,nginx,localhost,127.0.0.1
      - MAILER_FROM=${KIMAI_MAILER_FROM}
    volumes:
      - data:/opt/kimai/var/data
      - plugins:/opt/kimai/var/plugins
    networks:
      - default
      - proxy

networks:
  default:
    internal: true
  proxy:
    external: true

volumes:
  database:
  data:
  plugins:
