---
services:
  db:
    image: mariadb:10
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.hostname==rs1
          - node.labels.environment==production
          - node.labels.proxy!=true
      replicas: 1
    command:
      --transaction-isolation=READ-COMMITTED
      --binlog-format=ROW
      --skip-innodb-read-only-compressed
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${NEXTCLOUD_DB_ROOT_PASSWORD}
      - MYSQL_USER=nextcloud
    volumes:
      - database:/var/lib/mysql
    networks:
      - default

  redis:
    image: redis:alpine
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.hostname==rs1
          - node.labels.environment==production
          - node.labels.proxy!=true
      replicas: 1
    command: redis-server --requirepass "${NEXTCLOUD_REDIS_PASSWORD}"
    networks:
      - default

  app:
    image: nextcloud:27
    deploy:
      mode: replicated
      placement:
        constraints:
          - node.hostname==rs1
          - node.labels.environment==production
          - node.labels.proxy!=true
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.middlewares.nextcloud-dav.replacepathregex.regex=^/.well-known/ca(l|rd)dav
        - traefik.http.middlewares.nextcloud-dav.replacepathregex.replacement=https://$$1/remote.php/dav/
        - traefik.http.routers.nextcloud.entrypoints=websecure
        - traefik.http.routers.nextcloud.middlewares=nextcloud-dav,sts-headers
        - traefik.http.routers.nextcloud.rule=Host(`cloud.${APP_DOMAIN}`)
        - traefik.http.routers.nextcloud.tls.certresolver=letsencrypt
        - traefik.http.routers.nextcloud.tls=true
        - traefik.http.services.nextcloud.loadbalancer.server.port=80
        - traefik.swarm.network=proxy
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_HOST=db
      - MYSQL_PASSWORD=${NEXTCLOUD_DB_PASSWORD}
      - MYSQL_USER=nextcloud
      - NEXTCLOUD_TRUSTED_DOMAINS=cloud.${APP_DOMAIN}`),localhost,127.0.0.1
      - OVERWRITECLIURL=https://cloud.${APP_DOMAIN}`)
      - OVERWRITEHOST=cloud.${APP_DOMAIN}`)
      - OVERWRITEPROTOCOL=https
      - REDIS_HOST_PASSWORD=${NEXTCLOUD_REDIS_PASSWORD}
      - REDIS_HOST=redis
      - TRUSTED_PROXIES=172.0.0.1/8
    volumes:
      - data:/var/www/html
    networks:
      - default
      - proxy

networks:
  proxy:
    external: true

volumes:
  data:
  database:
