#!/usr/bin/env bash
# mise description="Start a minikube cluster"

minikube \
    --addons="csi-hostpath-driver,ingress,metrics-server,volumesnapshots" \
    --container-runtime="containerd" \
    --cpus="$MINIKUBE_CPUS" \
    --extra-disks="1" \
    --kubernetes-version="$MINIKUBE_KUBERNETES_VERSION" \
    --nodes="$MINIKUBE_NODE_COUNT" \
    --profile="$MINIKUBE_PROFILE" \
    start
